version: '3.1'

services:
  php:
    container_name: php
    image: php:8.2-apache
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    depends_on: [db]
    ports:
      - "1234:80"
    volumes:
      - ./php:/var/www/
    networks:
      - backroom-nt

  db:
    container_name: db
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "1111:5432"
    networks:
      - backroom-nt

  migration:
    container_name: migration
    image: flyway/flyway
    environment:
        FLYWAY_URL: ${FLYWAY_URL}
        FLYWAY_USER: ${DATABASE_USER}
        FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
        FLYWAY_SCHEMAS: ${FLYWAY_SCHEMAS}
        FLYWAY_LOCATIONS: ${FLYWAY_LOCATIONS}
    command: ['baseline', 'migrate', 'info']
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on: [db]
    networks:
      - backroom-nt

  myadmin:
    container_name: myadmin
    image: adminer
    restart: always
    networks:
      - backroom-nt
    ports:
      - "4321:8080"

networks:
  backroom-nt:
    driver: bridge


